// generated from bbqs.csv file
export const bbqs = [
  {
    "PARK_NAME": "SHEPHERD PLACE PARK",
    "SUBURB": "SHORNCLIFFE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "CASCADE DRIVE PARK (NO.20)",
    "SUBURB": "FOREST LAKE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "PAT RAFTER PARK",
    "SUBURB": "CARSELDINE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "SVOBODA PARK",
    "SUBURB": "KURABY",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "YOWOGGERA  PARK",
    "SUBURB": "ALBION",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "TERALBA PARK",
    "SUBURB": "EVERTON PARK",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "WALTON BRIDGE RESERVE",
    "SUBURB": "THE GAP",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "NOSWORTHY PARK",
    "SUBURB": "CORINDA",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "KEPERRA PICNIC GROUND PARK",
    "SUBURB": "FERNY GROVE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "MING-SHAN PARK",
    "SUBURB": "CALAMVALE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "RILATT PARK",
    "SUBURB": "WAVELL HEIGHTS",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "STRETTON COMMUNITY PARK",
    "SUBURB": "STRETTON",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "WYNNUM WADING POOL PARK",
    "SUBURB": "WYNNUM",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "SHOWGROUND PARK",
    "SUBURB": "NUDGEE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "MELROSE PARK",
    "SUBURB": "WOOLOOWIN",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "ROCKS RIVERSIDE PARK",
    "SUBURB": "SEVENTEEN MILE ROCKS",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "JOHN STEWART MEMORIAL PARK",
    "SUBURB": "BALD HILLS",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "WILLMINGTON PARK",
    "SUBURB": "ALDERLEY",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "BROADWATER PICNIC GROUND PARK",
    "SUBURB": "MANSFIELD",
    "ITEM_DESCRIPTION": "BBQ - WOOD SINGLE"
  },
  {
    "PARK_NAME": "LEN TREZONA PARK",
    "SUBURB": "ZILLMERE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "SUNSET PLACE PARK",
    "SUBURB": "MCDOWALL",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "DOWNEY PARK",
    "SUBURB": "WINDSOR",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "COL BENNET PARK",
    "SUBURB": "ALGESTER",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "WAKERLEY PARK",
    "SUBURB": "WAKERLEY",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "CARINDALE RECREATION RESERVE",
    "SUBURB": "CARINDALE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "SHERIFF PARK",
    "SUBURB": "WAKERLEY",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "FREE STREET PARK",
    "SUBURB": "NEWMARKET",
    "ITEM_DESCRIPTION": "BBQ - WOOD SINGLE"
  },
  {
    "PARK_NAME": "PACIFIC PARADE PARK",
    "SUBURB": "FOREST LAKE",
    "ITEM_DESCRIPTION": "BBQ - WOOD SINGLE"
  },
  {
    "PARK_NAME": "ANNA SMITH OBE QUOTA PARK",
    "SUBURB": "CARINDALE",
    "ITEM_DESCRIPTION": "BBQ - WOOD DOUBLE"
  },
  {
    "PARK_NAME": "COLMSLIE BEACH RESERVE",
    "SUBURB": "MURARRIE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "MT COOT-THA RESERVE",
    "SUBURB": "MOUNT COOT-THA",
    "ITEM_DESCRIPTION": "BBQ - GAS DOUBLE (SOLAR IGNITION)"
  },
  {
    "PARK_NAME": "MAIDSTONE STREET PARK",
    "SUBURB": "KELVIN GROVE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "BROADWATER PICNIC GROUND PARK",
    "SUBURB": "MANSFIELD",
    "ITEM_DESCRIPTION": "BBQ - WOOD SINGLE"
  },
  {
    "PARK_NAME": "MOORE PARK",
    "SUBURB": "INDOOROOPILLY",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "C.B.MOTT PARK",
    "SUBURB": "HOLLAND PARK",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "THOMAS McBRIDE PARK",
    "SUBURB": "PINKENBA",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "GARRETT PARK",
    "SUBURB": "RUNCORN",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "LAVARACK PARK",
    "SUBURB": "CAMP HILL",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "GREY GUMS PARK",
    "SUBURB": "KELVIN GROVE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "ROCKS RIVERSIDE PARK",
    "SUBURB": "SEVENTEEN MILE ROCKS",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "MT COOT-THA RESERVE",
    "SUBURB": "MOUNT COOT-THA",
    "ITEM_DESCRIPTION": "BBQ - GAS DOUBLE (SOLAR IGNITION)"
  },
  {
    "PARK_NAME": "FORT ROAD BUSHLANDS",
    "SUBURB": "OXLEY",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "HARDCASTLE PARK",
    "SUBURB": "HAWTHORNE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "MEADOWLANDS PICNIC GROUND PARK",
    "SUBURB": "TINGALPA",
    "ITEM_DESCRIPTION": "BBQ - WOOD SINGLE"
  },
  {
    "PARK_NAME": "BUCKINGHAM PLACE PARK",
    "SUBURB": "EIGHT MILE PLAINS",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "GUYATT PARK",
    "SUBURB": "ST LUCIA",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "TAYLOR BRIDGE RESERVE",
    "SUBURB": "CHELMER",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "SEDGLEY PARK",
    "SUBURB": "ALDERLEY",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "PRINCESS STREET PARK (NOS.5-21)",
    "SUBURB": "FAIRFIELD",
    "ITEM_DESCRIPTION": "BBQ - WOOD SINGLE"
  },
  {
    "PARK_NAME": "TENERIFFE PARK",
    "SUBURB": "TENERIFFE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "MANN PARK",
    "SUBURB": "WINDSOR",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "TINCHI TAMBA WETLANDS RESERVE",
    "SUBURB": "BALD HILLS",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "SANDGATE FORESHORES PARK",
    "SUBURB": "SANDGATE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "BAYSIDE PARK",
    "SUBURB": "MANLY",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "LEICESTER STREET PARK",
    "SUBURB": "COORPAROO",
    "ITEM_DESCRIPTION": "BBQ - WOOD SINGLE"
  },
  {
    "PARK_NAME": "RIVERVIEW FARM PARK",
    "SUBURB": "WESTLAKE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "7TH BRIGADE PARK",
    "SUBURB": "CHERMSIDE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "MARCHANT PARK",
    "SUBURB": "ASPLEY",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "FLAMETREE STREET PARK",
    "SUBURB": "BRIDGEMAN DOWNS",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "TOOWONG MEMORIAL PARK",
    "SUBURB": "TOOWONG",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "KOOKABURRA PARK - WEST",
    "SUBURB": "KARANA DOWNS",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "FRED FRANCIS PARK",
    "SUBURB": "BRACKEN RIDGE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "PLAISTED PLACE PARK",
    "SUBURB": "NORTHGATE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "NEW FARM PARK",
    "SUBURB": "NEW FARM",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "AVONDALE PARK",
    "SUBURB": "SINNAMON PARK",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "CALAMVALE DISTRICT PARK",
    "SUBURB": "CALAMVALE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "CALAMVALE DISTRICT PARK",
    "SUBURB": "CALAMVALE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "WILLIAMS PARK",
    "SUBURB": "RUNCORN",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "WHITES HILL RESERVE",
    "SUBURB": "CAMP HILL",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "TORRENS CRESCENT PARK",
    "SUBURB": "WAKERLEY",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "KEN FLETCHER PARK",
    "SUBURB": "TENNYSON",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "SETTLERS PARK",
    "SUBURB": "SINNAMON PARK",
    "ITEM_DESCRIPTION": "BBQ - WOOD SINGLE"
  },
  {
    "PARK_NAME": "ANZAC PARK",
    "SUBURB": "MOUNT COOT-THA",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "MAJESTIC PARK",
    "SUBURB": "COORPAROO",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "CHELSEA ROAD PARK (NOS.399-551)",
    "SUBURB": "RANSOME",
    "ITEM_DESCRIPTION": "BBQ - GAS DOUBLE"
  },
  {
    "PARK_NAME": "IRIS PLACE PARK",
    "SUBURB": "FITZGIBBON",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "KURINGGAI PARK",
    "SUBURB": "FITZGIBBON",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "MT COOT-THA RESERVE",
    "SUBURB": "MOUNT COOT-THA",
    "ITEM_DESCRIPTION": "BBQ - GAS DOUBLE (SOLAR IGNITION)"
  },
  {
    "PARK_NAME": "KEATING PARK",
    "SUBURB": "INDOOROOPILLY",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "MCCOOK PARK",
    "SUBURB": "NEWMARKET",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "GLINDEMANN PARK",
    "SUBURB": "HOLLAND PARK WEST",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "FREW PARK",
    "SUBURB": "MILTON",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "THE LAKE PARKLANDS",
    "SUBURB": "FOREST LAKE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "OXENHAM PARK",
    "SUBURB": "NUNDAH",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "KUNDU PARK",
    "SUBURB": "KELVIN GROVE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "DAINTREE PARK",
    "SUBURB": "FITZGIBBON",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "MT COOT-THA RESERVE",
    "SUBURB": "MOUNT COOT-THA",
    "ITEM_DESCRIPTION": "BBQ - GAS DOUBLE (SOLAR IGNITION)"
  },
  {
    "PARK_NAME": "MT COOT-THA RESERVE",
    "SUBURB": "MOUNT COOT-THA",
    "ITEM_DESCRIPTION": "BBQ - GAS DOUBLE (SOLAR IGNITION)"
  },
  {
    "PARK_NAME": "WEST END RIVERSIDE LANDS PARK",
    "SUBURB": "WEST END",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "JURAYELBA PLACE PARK",
    "SUBURB": "KEPERRA",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "NEWCOMB PARK",
    "SUBURB": "RIVERHILLS",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "MOGGILL DISTRICT SPORT PARK",
    "SUBURB": "MOGGILL",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "BANYO MEMORIAL PARK",
    "SUBURB": "BANYO",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "SHAW ESTATE PARK",
    "SUBURB": "WAVELL HEIGHTS",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "CAMERON ROCKS RESERVE",
    "SUBURB": "HAMILTON",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "SALISBURY RECREATION RESERVE",
    "SUBURB": "SALISBURY",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "SANDGATE SECOND LAGOON RESERVE",
    "SUBURB": "SANDGATE",
    "ITEM_DESCRIPTION": "BBQ - WOOD SINGLE"
  },
  {
    "PARK_NAME": "COL BENNET PARK",
    "SUBURB": "ALGESTER",
    "ITEM_DESCRIPTION": "BBQ - WOOD SINGLE"
  },
  {
    "PARK_NAME": "TRYON STREET PARK",
    "SUBURB": "UPPER MOUNT GRAVATT",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "CARL STREET PARK",
    "SUBURB": "WOOLLOONGABBA",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "GORDON PARK PLAYGROUND PARK",
    "SUBURB": "GORDON PARK",
    "ITEM_DESCRIPTION": "BBQ - WOOD SINGLE"
  },
  {
    "PARK_NAME": "MOGGILL FERRY RESERVE",
    "SUBURB": "MOGGILL",
    "ITEM_DESCRIPTION": "BBQ - GAS SINGLE (SOLAR IGNITION)"
  },
  {
    "PARK_NAME": "PERRIN PARK",
    "SUBURB": "TOOWONG",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "WALLY TATE PARK",
    "SUBURB": "KURABY",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "COLMSLIE BEACH RESERVE",
    "SUBURB": "MURARRIE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "JOHN PATTERSON PARK",
    "SUBURB": "CHERMSIDE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "SANDGATE FORESHORES PARK",
    "SUBURB": "SANDGATE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "THE LAKE PARKLANDS",
    "SUBURB": "FOREST LAKE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "TALISKER PLACE PARK",
    "SUBURB": "PARKINSON",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "LEACROFT ROAD PARK",
    "SUBURB": "BURBANK",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "SANDGATE FORESHORES PARK",
    "SUBURB": "SANDGATE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "BARRETT STREET PARK (WATER RESERVE)",
    "SUBURB": "BRACKEN RIDGE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "BARRETT STREET PARK (WATER RESERVE)",
    "SUBURB": "BRACKEN RIDGE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "DR VALENTINE McDOWALL PARK",
    "SUBURB": "MCDOWALL",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "JOHN GOSS RESERVE",
    "SUBURB": "CHERMSIDE WEST",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "AMAZONS PLACE PARK",
    "SUBURB": "JINDALEE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "SANDGATE FORESHORES PARK",
    "SUBURB": "SANDGATE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "SALISBURY RECREATION RESERVE",
    "SUBURB": "SALISBURY",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "BILL MOORE PARK",
    "SUBURB": "SALISBURY",
    "ITEM_DESCRIPTION": "BBQ - WOOD SINGLE"
  },
  {
    "PARK_NAME": "JOY TAYLOR PARK",
    "SUBURB": "COOPERS PLAINS",
    "ITEM_DESCRIPTION": "BBQ - WOOD SINGLE"
  },
  {
    "PARK_NAME": "MIKADO STREET PARK",
    "SUBURB": "ASCOT",
    "ITEM_DESCRIPTION": "BBQ - WOOD SINGLE"
  },
  {
    "PARK_NAME": "MAISIE DIXON PARK",
    "SUBURB": "EIGHT MILE PLAINS",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "7TH BRIGADE PARK",
    "SUBURB": "CHERMSIDE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "WENDON WAY PARK",
    "SUBURB": "BRIDGEMAN DOWNS",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "BROOKFIELD RECREATION RESERVE",
    "SUBURB": "BROOKFIELD",
    "ITEM_DESCRIPTION": "BBQ - WOOD SINGLE"
  },
  {
    "PARK_NAME": "VOGLER PARK",
    "SUBURB": "SUNNYBANK HILLS",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "FRANK ROBERTS PARK",
    "SUBURB": "WAVELL HEIGHTS",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "SHERWOOD ARBORETUM",
    "SUBURB": "SHERWOOD",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "ORLEIGH PARK",
    "SUBURB": "WEST END",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "FREDERICK ANNAND PARK",
    "SUBURB": "CHERMSIDE WEST",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "MURARRIE RECREATION GROUND",
    "SUBURB": "MURARRIE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "CHURCHILL CIRCUIT PARK",
    "SUBURB": "BANYO",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "TINCHI TAMBA WETLANDS RESERVE",
    "SUBURB": "BALD HILLS",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "PACIFIC PARADE PARK",
    "SUBURB": "FOREST LAKE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "SANDGATE FORESHORES PARK",
    "SUBURB": "SANDGATE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "MINGOOLA PARK",
    "SUBURB": "MURARRIE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "WISHART COMMUNITY PARK",
    "SUBURB": "WISHART",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "CLIFF STREET PARK",
    "SUBURB": "SANDGATE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "TILLACK PARK",
    "SUBURB": "MANSFIELD",
    "ITEM_DESCRIPTION": "BBQ - WOOD SINGLE"
  },
  {
    "PARK_NAME": "FIG TREE COMMON PARK",
    "SUBURB": "FIG TREE POCKET",
    "ITEM_DESCRIPTION": "BBQ - WOOD SINGLE"
  },
  {
    "PARK_NAME": "CORMORANT STREET PARK",
    "SUBURB": "INALA",
    "ITEM_DESCRIPTION": "BBQ - WOOD SINGLE"
  },
  {
    "PARK_NAME": "MOORA PARK",
    "SUBURB": "SHORNCLIFFE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "CAPTAIN BURKE PARK",
    "SUBURB": "KANGAROO POINT",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "KANGAROO POINT CLIFFS PARK",
    "SUBURB": "KANGAROO POINT",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "KEATING PARK",
    "SUBURB": "INDOOROOPILLY",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "TARANA STREET PARK",
    "SUBURB": "CAMP HILL",
    "ITEM_DESCRIPTION": "BBQ - WOOD SINGLE"
  },
  {
    "PARK_NAME": "BRUSH BOX PLACE PARK",
    "SUBURB": "HEATHWOOD",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "MT COOT-THA RESERVE",
    "SUBURB": "MOUNT COOT-THA",
    "ITEM_DESCRIPTION": "BBQ - WOOD SINGLE"
  },
  {
    "PARK_NAME": "MT COOT-THA RESERVE",
    "SUBURB": "MOUNT COOT-THA",
    "ITEM_DESCRIPTION": "BBQ - GAS DOUBLE (SOLAR IGNITION)"
  },
  {
    "PARK_NAME": "WESTAWAY PARK (MOGGILL)",
    "SUBURB": "MOGGILL",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "MT COOT-THA RESERVE",
    "SUBURB": "MOUNT COOT-THA",
    "ITEM_DESCRIPTION": "BBQ - GAS DOUBLE (SOLAR IGNITION)"
  },
  {
    "PARK_NAME": "MT COOT-THA RESERVE",
    "SUBURB": "MOUNT COOT-THA",
    "ITEM_DESCRIPTION": "BBQ - GAS DOUBLE (SOLAR IGNITION)"
  },
  {
    "PARK_NAME": "ASPLEY REST PARK",
    "SUBURB": "CARSELDINE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "MACKENZIE PARK",
    "SUBURB": "MACKENZIE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "SID LODER PARK",
    "SUBURB": "MITCHELTON",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "ROSEBANK SQUARE",
    "SUBURB": "SALISBURY",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "HAZEL STREET PARK",
    "SUBURB": "HEATHWOOD",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "BULIMBA RIVERSIDE PARK",
    "SUBURB": "BULIMBA",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "JINDALEE BOAT RAMP PARK",
    "SUBURB": "JINDALEE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "JINDALEE BOAT RAMP PARK",
    "SUBURB": "JINDALEE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "DAINTREE DRIVE PARK (NO.65)",
    "SUBURB": "PARKINSON",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "NEW FARM PARK",
    "SUBURB": "NEW FARM",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "LOTA CAMPING RESERVE",
    "SUBURB": "LOTA",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "NEW FARM PARK",
    "SUBURB": "NEW FARM",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "MARTINDALE STREET PARK",
    "SUBURB": "CHERMSIDE WEST",
    "ITEM_DESCRIPTION": "BBQ - WOOD SINGLE"
  },
  {
    "PARK_NAME": "TOOWONG MEMORIAL PARK",
    "SUBURB": "TOOWONG",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "MARMINDIE STREET PARK",
    "SUBURB": "CHAPEL HILL",
    "ITEM_DESCRIPTION": "BBQ - WOOD SINGLE"
  },
  {
    "PARK_NAME": "NIXON PARK",
    "SUBURB": "OXLEY",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "JAMBOREE LIONS COMMUNITY PARK",
    "SUBURB": "MIDDLE PARK",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "NUDGEE BEACH RESERVE",
    "SUBURB": "NUDGEE BEACH",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "SANDGATE FORESHORES PARK",
    "SUBURB": "SANDGATE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "SANDGATE FORESHORES PARK",
    "SUBURB": "SANDGATE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "BUNDABAH DRIVE PARK",
    "SUBURB": "CALAMVALE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "MACQUARIE WAY PARK (NO.123)",
    "SUBURB": "DREWVALE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "MORTIMER ROAD PARK",
    "SUBURB": "ACACIA RIDGE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "BOWDEN PARK",
    "SUBURB": "GEEBUNG",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "GRACEVILLE RIVERSIDE PARKLANDS",
    "SUBURB": "GRACEVILLE",
    "ITEM_DESCRIPTION": "BBQ - WOOD SINGLE"
  },
  {
    "PARK_NAME": "BOLES STREET PARK",
    "SUBURB": "STAFFORD",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "SPRINGFIELD CRESCENT PARK",
    "SUBURB": "PARKINSON",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "WALTON BRIDGE RESERVE",
    "SUBURB": "THE GAP",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "CARNARVON WAY PARK",
    "SUBURB": "MURARRIE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "COX PARK",
    "SUBURB": "LOTA",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "BERYL ROBERTS PARK",
    "SUBURB": "COOPERS PLAINS",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "LANHAM PARK",
    "SUBURB": "GRANGE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "CHESTER PARK RESERVE",
    "SUBURB": "MOUNT GRAVATT EAST",
    "ITEM_DESCRIPTION": "BBQ - WOOD SINGLE"
  },
  {
    "PARK_NAME": "JOHN PATTERSON PARK",
    "SUBURB": "CHERMSIDE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "NORTHSHORE RIVERSIDE PARK",
    "SUBURB": "HAMILTON",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "NORTHSHORE RIVERSIDE PARK",
    "SUBURB": "HAMILTON",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "FREW PARK",
    "SUBURB": "MILTON",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "YERONGA MEMORIAL PARK",
    "SUBURB": "YERONGA",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "ANZAC PARK",
    "SUBURB": "MOUNT COOT-THA",
    "ITEM_DESCRIPTION": "BBQ - WOOD SINGLE"
  },
  {
    "PARK_NAME": "CAPE ARID PARK",
    "SUBURB": "FITZGIBBON",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "KEATING PARK",
    "SUBURB": "INDOOROOPILLY",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "THE LAKE PARKLANDS",
    "SUBURB": "FOREST LAKE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "CLARINA STREET PARK",
    "SUBURB": "CHAPEL HILL",
    "ITEM_DESCRIPTION": "BBQ - WOOD SINGLE"
  },
  {
    "PARK_NAME": "MT COOT-THA RESERVE",
    "SUBURB": "MOUNT COOT-THA",
    "ITEM_DESCRIPTION": "BBQ - GAS DOUBLE (SOLAR IGNITION)"
  },
  {
    "PARK_NAME": "OLD SHORELINE PARK",
    "SUBURB": "HAMILTON",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "CAPTAIN BURKE PARK",
    "SUBURB": "KANGAROO POINT",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "DONNA PHILP PARK",
    "SUBURB": "BOONDALL",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "GREENWAYS ESPLANADE PARK",
    "SUBURB": "PARKINSON",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "NIXON PARK",
    "SUBURB": "OXLEY",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "WHISTLER PLACE PARK",
    "SUBURB": "PALLARA",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "HERCULES STREET PARK",
    "SUBURB": "HAMILTON",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "STRICKLAND TERRACE PARK",
    "SUBURB": "SHERWOOD",
    "ITEM_DESCRIPTION": "BBQ - WOOD SINGLE"
  },
  {
    "PARK_NAME": "WARRIL PARKLAND",
    "SUBURB": "LARAPINTA",
    "ITEM_DESCRIPTION": "BBQ - GAS DOUBLE"
  },
  {
    "PARK_NAME": "MINDONA ROTARY PARK",
    "SUBURB": "WISHART",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "ROBINSON PARK (FAIRFIELD)",
    "SUBURB": "FAIRFIELD",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "COWLISHAW STREET PARK",
    "SUBURB": "BOWEN HILLS",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "CASCADE DRIVE PARK (NO.25)",
    "SUBURB": "FOREST LAKE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "ROXWELL STREET PARK",
    "SUBURB": "FOREST LAKE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "GREGORY PARK",
    "SUBURB": "MILTON",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "SOLAR PARK",
    "SUBURB": "BRIDGEMAN DOWNS",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "THE RAFTING GROUND PARK",
    "SUBURB": "BROOKFIELD",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "TOOHEY FOREST PARK",
    "SUBURB": "NATHAN",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "7TH BRIGADE PARK",
    "SUBURB": "CHERMSIDE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "NEAL MACROSSAN PLAYGROUND PARK",
    "SUBURB": "PADDINGTON",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "BOYD TERRACE PARK",
    "SUBURB": "BROOKFIELD",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "BOYD PARK",
    "SUBURB": "NUNDAH",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "WILSON PARK",
    "SUBURB": "NORMAN PARK",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "BOORABBIN PICNIC GROUND",
    "SUBURB": "WISHART",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "NORMAN BUCHAN PARK",
    "SUBURB": "BARDON",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "HERBERT STREET PARK",
    "SUBURB": "LOTA",
    "ITEM_DESCRIPTION": "BBQ - WOOD SINGLE"
  },
  {
    "PARK_NAME": "ALGESTER ROAD PARK (NO.515)",
    "SUBURB": "PARKINSON",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "MYRTLETOWN RESERVE",
    "SUBURB": "PINKENBA",
    "ITEM_DESCRIPTION": "BBQ - WOOD SINGLE"
  },
  {
    "PARK_NAME": "BANCROFT PARK",
    "SUBURB": "KELVIN GROVE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "NUDGEE BEACH RESERVE",
    "SUBURB": "NUDGEE BEACH",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "YIMBUN PARK",
    "SUBURB": "SUNNYBANK",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "SHERIFF PARK",
    "SUBURB": "WAKERLEY",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "ORLEIGH PARK",
    "SUBURB": "WEST END",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "COLMSLIE BEACH RESERVE",
    "SUBURB": "MURARRIE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "COLMSLIE BEACH RESERVE",
    "SUBURB": "MURARRIE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "SANDGATE THIRD LAGOON RESERVE",
    "SUBURB": "BRIGHTON",
    "ITEM_DESCRIPTION": "BBQ - WOOD SINGLE"
  },
  {
    "PARK_NAME": "KIANAWAH ROAD PARK (NO.330)",
    "SUBURB": "WYNNUM WEST",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "WILCANNIA PARK",
    "SUBURB": "ASHGROVE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "KANGAROO POINT CLIFFS PARK",
    "SUBURB": "KANGAROO POINT",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "KIANAWAH ROAD PARK (NO.330)",
    "SUBURB": "WYNNUM WEST",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "KANGAROO POINT CLIFFS PARK",
    "SUBURB": "KANGAROO POINT",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "KURILPA POINT PARK",
    "SUBURB": "SOUTH BRISBANE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "BOOKER PLACE PARK",
    "SUBURB": "BELLBOWRIE",
    "ITEM_DESCRIPTION": "BBQ - WOOD SINGLE"
  },
  {
    "PARK_NAME": "ROCKS RIVERSIDE PARK",
    "SUBURB": "SEVENTEEN MILE ROCKS",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "UPPER KEDRON RECREATION RESERVE",
    "SUBURB": "UPPER KEDRON",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "YOWOGGERA  PARK",
    "SUBURB": "ALBION",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "SANDGATE SECOND LAGOON RESERVE",
    "SUBURB": "SANDGATE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "MT COOT-THA RESERVE",
    "SUBURB": "MOUNT COOT-THA",
    "ITEM_DESCRIPTION": "BBQ - GAS DOUBLE (SOLAR IGNITION)"
  },
  {
    "PARK_NAME": "SEABROOK CIRCUIT PARK",
    "SUBURB": "WESTLAKE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "TUCKEROO PARK",
    "SUBURB": "NUDGEE BEACH",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "FORT ROAD BUSHLANDS",
    "SUBURB": "OXLEY",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "ROY HARVEY PARK",
    "SUBURB": "STAFFORD",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "HEATHWOOD PARK",
    "SUBURB": "HEATHWOOD",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "BEDGOOD PARK",
    "SUBURB": "MILTON",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "KALINGA PARK",
    "SUBURB": "CLAYFIELD",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "KALINGA PARK",
    "SUBURB": "CLAYFIELD",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "NEW FARM PARK",
    "SUBURB": "NEW FARM",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "DUTTON PARK",
    "SUBURB": "DUTTON PARK",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "THE BEIRNE PARK",
    "SUBURB": "HENDRA",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "GRACEVILLE RIVERSIDE PARKLANDS",
    "SUBURB": "GRACEVILLE",
    "ITEM_DESCRIPTION": "BBQ - WOOD SINGLE"
  },
  {
    "PARK_NAME": "NEW FARM PARK",
    "SUBURB": "NEW FARM",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "MATISSE STREET PARK",
    "SUBURB": "CARSELDINE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "TINCHI TAMBA WETLANDS RESERVE",
    "SUBURB": "BALD HILLS",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "GRENIER PARK",
    "SUBURB": "ACACIA RIDGE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "KING STREET PARK",
    "SUBURB": "KURABY",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "JACARANDA PARK",
    "SUBURB": "YERONGA",
    "ITEM_DESCRIPTION": "BBQ - WOOD SINGLE"
  },
  {
    "PARK_NAME": "HAYWAL STREET PARK",
    "SUBURB": "TAIGUM",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "KOOKABURRA PARK - WEST",
    "SUBURB": "KARANA DOWNS",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "KEITH PAYNE PARK",
    "SUBURB": "STAFFORD",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "FREW PARK",
    "SUBURB": "MILTON",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "CALAMVALE DISTRICT PARK",
    "SUBURB": "CALAMVALE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "LOTA CAMPING RESERVE",
    "SUBURB": "LOTA",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "SIR JOHN CHANDLER PARK",
    "SUBURB": "INDOOROOPILLY",
    "ITEM_DESCRIPTION": "BBQ - WOOD SINGLE"
  },
  {
    "PARK_NAME": "CAPE ARID PARK",
    "SUBURB": "FITZGIBBON",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "MT COOT-THA RESERVE",
    "SUBURB": "MOUNT COOT-THA",
    "ITEM_DESCRIPTION": "BBQ - GAS DOUBLE (SOLAR IGNITION)"
  },
  {
    "PARK_NAME": "GEMSTONE CRESCENT PARK",
    "SUBURB": "ACACIA RIDGE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "MACARANGA CRESCENT PARK",
    "SUBURB": "CARSELDINE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "MONTROSE PARK",
    "SUBURB": "CORINDA",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "BURNIE BRAE PARK",
    "SUBURB": "CHERMSIDE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "STRAWBERRY FIELDS PLACE",
    "SUBURB": "ROCHEDALE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "MUSGRAVE PARK",
    "SUBURB": "SOUTH BRISBANE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "TOOHEY FOREST PARK",
    "SUBURB": "NATHAN",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "MCKOY STREET PARK",
    "SUBURB": "COOPERS PLAINS",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "MCPHERSON PARK",
    "SUBURB": "BRACKEN RIDGE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "TARRAGINDI RECREATION RESERVE",
    "SUBURB": "TARRAGINDI",
    "ITEM_DESCRIPTION": "BBQ - WOOD SINGLE"
  },
  {
    "PARK_NAME": "PALLARA PARK",
    "SUBURB": "PALLARA",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "PORTER'S PADDOCK PARK",
    "SUBURB": "TINGALPA",
    "ITEM_DESCRIPTION": "BBQ - GAS DOUBLE (SOLAR IGNITION)"
  },
  {
    "PARK_NAME": "HERCULES STREET PARK",
    "SUBURB": "HAMILTON",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "ANZAC PARK",
    "SUBURB": "MOUNT COOT-THA",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "SIR JOHN CHANDLER PARK",
    "SUBURB": "INDOOROOPILLY",
    "ITEM_DESCRIPTION": "BBQ - WOOD SINGLE"
  },
  {
    "PARK_NAME": "MT COOT-THA RESERVE",
    "SUBURB": "MOUNT COOT-THA",
    "ITEM_DESCRIPTION": "BBQ - WOOD SINGLE"
  },
  {
    "PARK_NAME": "KEV HOOPER MEMORIAL PARK",
    "SUBURB": "INALA",
    "ITEM_DESCRIPTION": "BBQ - GAS SINGLE"
  },
  {
    "PARK_NAME": "WARRIL PARKLAND",
    "SUBURB": "LARAPINTA",
    "ITEM_DESCRIPTION": "BBQ - GAS DOUBLE"
  },
  {
    "PARK_NAME": "KATHLEEN STREET PARK",
    "SUBURB": "RICHLANDS",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "GRINSTEAD PARK",
    "SUBURB": "ALDERLEY",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "C.J.GREENFIELD COMPLEX PARK",
    "SUBURB": "RICHLANDS",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "SHERWOOD ARBORETUM",
    "SUBURB": "SHERWOOD",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "FAIRFIELD PARK",
    "SUBURB": "FAIRFIELD",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "DAINTREE DRIVE PARK (NO.65)",
    "SUBURB": "PARKINSON",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "BOWMAN PARK",
    "SUBURB": "BARDON",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "SOAMES STREET PARK",
    "SUBURB": "EVERTON PARK",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "MOORA PARK",
    "SUBURB": "SHORNCLIFFE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "SANCTUARY DRIVE PARK",
    "SUBURB": "FOREST LAKE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "MT COOT-THA RESERVE",
    "SUBURB": "MOUNT COOT-THA",
    "ITEM_DESCRIPTION": "BBQ - WOOD SINGLE"
  },
  {
    "PARK_NAME": "JOHN GOSS RESERVE",
    "SUBURB": "CHERMSIDE WEST",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "FRANK SLEEMAN PARK",
    "SUBURB": "BOONDALL",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "BULIMBA RIVERSIDE PARK",
    "SUBURB": "BULIMBA",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "NUDGEE BEACH RESERVE",
    "SUBURB": "NUDGEE BEACH",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "DECKER PARK",
    "SUBURB": "BRIGHTON",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "ROSEMOUNT PARK",
    "SUBURB": "SINNAMON PARK",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "BEDFORD PLAYGROUND PARK",
    "SUBURB": "SPRING HILL",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "ORLEIGH PARK",
    "SUBURB": "WEST END",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "DASH STREET PARK",
    "SUBURB": "KEPERRA",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "BRAMPTON STREET PARK",
    "SUBURB": "EIGHT MILE PLAINS",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "LAMBERT MCBRIDE PARK",
    "SUBURB": "ZILLMERE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "TONKS STREET PARK",
    "SUBURB": "MOOROOKA",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "HAMISH STREET PARK",
    "SUBURB": "CALAMVALE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "MILTON PARK",
    "SUBURB": "MILTON",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "CROSBY PARK",
    "SUBURB": "ALBION",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "BLISS STREET PARK (NO.39)",
    "SUBURB": "GAYTHORNE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "STUMERS ROAD RESERVE",
    "SUBURB": "MOUNT CROSBY",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "SANDGATE THIRD LAGOON RESERVE",
    "SUBURB": "BRIGHTON",
    "ITEM_DESCRIPTION": "BBQ - WOOD SINGLE"
  },
  {
    "PARK_NAME": "CAPTAIN DOUG HISLOP PARK",
    "SUBURB": "MURARRIE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "CALLIOPE CIRCUIT PARK",
    "SUBURB": "MURARRIE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "MT COOT-THA RESERVE",
    "SUBURB": "MOUNT COOT-THA",
    "ITEM_DESCRIPTION": "BBQ - GAS DOUBLE"
  },
  {
    "PARK_NAME": "C.B.MOTT PARK",
    "SUBURB": "HOLLAND PARK",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "CAROLE PARK COMMUNITY PARK",
    "SUBURB": "ELLEN GROVE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "SANDGATE SECOND LAGOON RESERVE",
    "SUBURB": "SANDGATE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "WILLIAMINA PARK",
    "SUBURB": "EAST BRISBANE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "BRUSH BOX PLACE PARK",
    "SUBURB": "HEATHWOOD",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "MT COOT-THA RESERVE",
    "SUBURB": "MOUNT COOT-THA",
    "ITEM_DESCRIPTION": "BBQ - WOOD SINGLE"
  },
  {
    "PARK_NAME": "TURRBAL PLACE PARK",
    "SUBURB": "ASPLEY",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "CANTERBURY PARK",
    "SUBURB": "BALD HILLS",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "BRADSHAW PARK",
    "SUBURB": "LUTWYCHE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "KIANAWAH PARK",
    "SUBURB": "TINGALPA",
    "ITEM_DESCRIPTION": "BBQ - WOOD SINGLE"
  },
  {
    "PARK_NAME": "D.M.HENDERSON PARK",
    "SUBURB": "MACGREGOR",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "SHE-OAK PARK",
    "SUBURB": "TINGALPA",
    "ITEM_DESCRIPTION": "BBQ - WOOD SINGLE"
  },
  {
    "PARK_NAME": "GUYATT PARK",
    "SUBURB": "ST LUCIA",
    "ITEM_DESCRIPTION": "BBQ - WOOD SINGLE"
  },
  {
    "PARK_NAME": "ROWLINSON PARK",
    "SUBURB": "YERONGA",
    "ITEM_DESCRIPTION": "BBQ - WOOD SINGLE"
  },
  {
    "PARK_NAME": "REAL PARK",
    "SUBURB": "EAST BRISBANE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "DOWNFALL CREEK RESERVE",
    "SUBURB": "VIRGINIA",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "JINDALEE BOAT RAMP PARK",
    "SUBURB": "JINDALEE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "JOHN WALKER PLACE",
    "SUBURB": "YERONGA",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "LAKEWOOD AVENUE PARK",
    "SUBURB": "PARKINSON",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "CAPTAIN BURKE PARK",
    "SUBURB": "KANGAROO POINT",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "EDENBROOKE PARK",
    "SUBURB": "SEVENTEEN MILE ROCKS",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "WYNNUM WADING POOL PARK",
    "SUBURB": "WYNNUM",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "SANDGATE FORESHORES PARK",
    "SUBURB": "SANDGATE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "TOOHEY FOREST PARK",
    "SUBURB": "NATHAN",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "7TH BRIGADE PARK",
    "SUBURB": "CHERMSIDE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "MORTIMER ROAD PARK",
    "SUBURB": "ACACIA RIDGE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "BELLEVUE AVENUE PARK",
    "SUBURB": "GAYTHORNE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "SURBITON COURT PARK",
    "SUBURB": "CARINDALE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "RON GOELDNER PARK",
    "SUBURB": "YERONGA",
    "ITEM_DESCRIPTION": "BBQ - WOOD SINGLE"
  },
  {
    "PARK_NAME": "SVOBODA PARK",
    "SUBURB": "KURABY",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "DUTTON PARK",
    "SUBURB": "DUTTON PARK",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "KOOKABURRA PARK - WEST",
    "SUBURB": "KARANA DOWNS",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "BENELONG PARK",
    "SUBURB": "KEDRON",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "SELKIRK CRESCENT PARK",
    "SUBURB": "UPPER KEDRON",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "WATERFRONT PARK",
    "SUBURB": "NEWSTEAD",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "KANGAROO POINT CLIFFS PARK",
    "SUBURB": "KANGAROO POINT",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "LOTA CAMPING RESERVE",
    "SUBURB": "LOTA",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "V.MCN.PEACHEY PARK",
    "SUBURB": "OXLEY",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "FRANK WATERS PARK",
    "SUBURB": "ASHGROVE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "BENBEK CIRCUIT PARK",
    "SUBURB": "SUNNYBANK HILLS",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "LANHAM PARK",
    "SUBURB": "GRANGE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "PASK FAMILY PARK",
    "SUBURB": "ROCHEDALE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "HEINRICH GERNS PARK",
    "SUBURB": "WAVELL HEIGHTS",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "GLINDEMANN PARK",
    "SUBURB": "HOLLAND PARK WEST",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "SANDGATE THIRD LAGOON RESERVE",
    "SUBURB": "BRIGHTON",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "ST VINCENTS ROAD PARK",
    "SUBURB": "NUDGEE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "TOM O'NEIL PARK",
    "SUBURB": "OXLEY",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "BUNYAPA PARK",
    "SUBURB": "WEST END",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "GIBSON PLACE PARK",
    "SUBURB": "HOLLAND PARK WEST",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "MCCASKILL RD PARK",
    "SUBURB": "PULLENVALE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "ASCOT PARK",
    "SUBURB": "ASCOT",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "HAWTHORNE PARK",
    "SUBURB": "HAWTHORNE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "MT COOT-THA RESERVE",
    "SUBURB": "MOUNT COOT-THA",
    "ITEM_DESCRIPTION": "BBQ - GAS DOUBLE (SOLAR IGNITION)"
  },
  {
    "PARK_NAME": "DALKEITH PARK",
    "SUBURB": "KALINGA",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "MT COOT-THA RESERVE",
    "SUBURB": "MOUNT COOT-THA",
    "ITEM_DESCRIPTION": "BBQ - WOOD SINGLE"
  },
  {
    "PARK_NAME": "MT COOT-THA RESERVE",
    "SUBURB": "MOUNT COOT-THA",
    "ITEM_DESCRIPTION": "BBQ - WOOD SINGLE"
  },
  {
    "PARK_NAME": "RIKKI BAILEY PARK",
    "SUBURB": "OXLEY",
    "ITEM_DESCRIPTION": "BBQ - WOOD SINGLE"
  },
  {
    "PARK_NAME": "PACIFIC PARADE PARK",
    "SUBURB": "FOREST LAKE",
    "ITEM_DESCRIPTION": "BBQ - WOOD SINGLE"
  },
  {
    "PARK_NAME": "MT COOT-THA RESERVE",
    "SUBURB": "MOUNT COOT-THA",
    "ITEM_DESCRIPTION": "BBQ - WOOD SINGLE"
  },
  {
    "PARK_NAME": "KEONG PARK",
    "SUBURB": "STAFFORD",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "JAMES FRENEY PARK",
    "SUBURB": "ACACIA RIDGE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "ALDREN STREET PARK",
    "SUBURB": "STAFFORD HEIGHTS",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "NUDGEE WATERHOLE RESERVE",
    "SUBURB": "NUDGEE",
    "ITEM_DESCRIPTION": "BBQ - GAS DOUBLE (SOLAR IGNITION)"
  },
  {
    "PARK_NAME": "ORIEL PARK",
    "SUBURB": "ASCOT",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "ALLAWAH STREET PARK",
    "SUBURB": "YEERONGPILLY",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "BILLABONG PLACE PARK",
    "SUBURB": "PARKINSON",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "BILL BROWN SPORTS RESERVE",
    "SUBURB": "FITZGIBBON",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "BLUE RANGE DRIVE PARK",
    "SUBURB": "ALGESTER",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "COLMSLIE BEACH RESERVE",
    "SUBURB": "MURARRIE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE (SOLAR 12V)"
  },
  {
    "PARK_NAME": "BARRETT STREET PARK (WATER RESERVE)",
    "SUBURB": "BRACKEN RIDGE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "BARRETT STREET PARK (WATER RESERVE)",
    "SUBURB": "BRACKEN RIDGE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "BILL MCFARLANE PARK",
    "SUBURB": "WAKERLEY",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "WYNNUM WADING POOL PARK",
    "SUBURB": "WYNNUM",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "MOWBRAY PARK",
    "SUBURB": "EAST BRISBANE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "BRIGHTON PARK",
    "SUBURB": "BRIGHTON",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "ROCKS RIVERSIDE PARK",
    "SUBURB": "SEVENTEEN MILE ROCKS",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "O'CALLAGHAN PARK",
    "SUBURB": "ZILLMERE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "JOHN TUCKER PARK",
    "SUBURB": "EVERTON PARK",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "LAVARACK PARK",
    "SUBURB": "CAMP HILL",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "KITCHENER PARK",
    "SUBURB": "WYNNUM",
    "ITEM_DESCRIPTION": "BBQ - WOOD SINGLE"
  },
  {
    "PARK_NAME": "KANGAROO POINT CLIFFS PARK",
    "SUBURB": "KANGAROO POINT",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "MOWBRAY PARK",
    "SUBURB": "EAST BRISBANE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "RAVEN STREET RESERVE",
    "SUBURB": "CHERMSIDE WEST",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "RAYMOND PARK",
    "SUBURB": "KANGAROO POINT",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "THOMPSON ESTATE RESERVE",
    "SUBURB": "GREENSLOPES",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "BLISS STREET PARK (LOT 29)",
    "SUBURB": "GAYTHORNE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "CRIBB ROAD PARK",
    "SUBURB": "CARINDALE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "MT COOT-THA RESERVE",
    "SUBURB": "MOUNT COOT-THA",
    "ITEM_DESCRIPTION": "BBQ - WOOD SINGLE"
  },
  {
    "PARK_NAME": "BROADWATER PICNIC GROUND PARK",
    "SUBURB": "MANSFIELD",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "KANGAROO POINT CLIFFS PARK",
    "SUBURB": "KANGAROO POINT",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "MT CROSBY SPORTSGROUND",
    "SUBURB": "CHUWAR",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "FERGUSON PARK (ENOGGERA)",
    "SUBURB": "ENOGGERA",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "SANDGATE SECOND LAGOON RESERVE",
    "SUBURB": "SANDGATE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "E. E. MCCASKIE OVAL",
    "SUBURB": "KELVIN GROVE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "KEONG PARK",
    "SUBURB": "STAFFORD",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "HEATH PARK",
    "SUBURB": "EAST BRISBANE",
    "ITEM_DESCRIPTION": "BBQ - WOOD SINGLE"
  },
  {
    "PARK_NAME": "NEW FARM PARK",
    "SUBURB": "NEW FARM",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "GEORGE CLAYTON PARK",
    "SUBURB": "MANLY",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "NEW FARM PARK",
    "SUBURB": "NEW FARM",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "TERALBA PARK",
    "SUBURB": "EVERTON PARK",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "CECCATO PARK",
    "SUBURB": "CARSELDINE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "KOKODA PARK",
    "SUBURB": "GORDON PARK",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "MERRI MERRI PARK",
    "SUBURB": "CHAPEL HILL",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "DURELLA STREET PARK",
    "SUBURB": "DURACK",
    "ITEM_DESCRIPTION": "BBQ - WOOD SINGLE"
  },
  {
    "PARK_NAME": "D.M.HENDERSON PARK",
    "SUBURB": "MACGREGOR",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "AMAZONS PLACE PARK",
    "SUBURB": "JINDALEE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "THE BEIRNE PARK",
    "SUBURB": "HENDRA",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "A.R.C.HILL PARK",
    "SUBURB": "VIRGINIA",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "KINGFISHER PARK",
    "SUBURB": "KENMORE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "NORTHUMBRIA ROAD PARK",
    "SUBURB": "BOONDALL",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "LES ATKINSON PARK",
    "SUBURB": "SUNNYBANK",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "SANDGATE FORESHORES PARK",
    "SUBURB": "SANDGATE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "SANDGATE FORESHORES PARK",
    "SUBURB": "SANDGATE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "SANDGATE FORESHORES PARK",
    "SUBURB": "SANDGATE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "ANNA SMITH OBE QUOTA PARK",
    "SUBURB": "CARINDALE",
    "ITEM_DESCRIPTION": "BBQ - WOOD SINGLE"
  },
  {
    "PARK_NAME": "FIG TREE POINT PARK (ROAD RESERVE)",
    "SUBURB": "LOTA",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "LES ATKINSON PARK",
    "SUBURB": "SUNNYBANK",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "ROBERT MITCHELL PARK",
    "SUBURB": "SUNNYBANK HILLS",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "JOHN WALKER PLACE",
    "SUBURB": "YERONGA",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "HONEYSUCKLE WAY PARK",
    "SUBURB": "CALAMVALE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "MORTIMER ROAD PARK",
    "SUBURB": "ACACIA RIDGE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "CORBIE STREET PARK",
    "SUBURB": "ASHGROVE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "SVOBODA PARK",
    "SUBURB": "KURABY",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "MT CROSBY SPORTSGROUND",
    "SUBURB": "CHUWAR",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "HEDLEY BARKER PARK",
    "SUBURB": "ASPLEY",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "DORRINGTON PARK",
    "SUBURB": "ASHGROVE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "FREW PARK",
    "SUBURB": "MILTON",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "FREW PARK",
    "SUBURB": "MILTON",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "JAMBOREE PARK",
    "SUBURB": "JAMBOREE HEIGHTS",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "CALAMVALE DISTRICT PARK",
    "SUBURB": "CALAMVALE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "BELDALE PARK",
    "SUBURB": "SUNNYBANK HILLS",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "JAGERA PARK",
    "SUBURB": "RUNCORN",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "BROADWATER PICNIC GROUND PARK",
    "SUBURB": "MANSFIELD",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "PEGG'S PARK",
    "SUBURB": "MOOROOKA",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "TOOHEY FOREST PARK",
    "SUBURB": "NATHAN",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "KANGAROO POINT CLIFFS PARK",
    "SUBURB": "KANGAROO POINT",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "PENHALIGON PARK",
    "SUBURB": "CHAPEL HILL",
    "ITEM_DESCRIPTION": "BBQ - WOOD SINGLE"
  },
  {
    "PARK_NAME": "OXFORD GROVE PARK",
    "SUBURB": "KEPERRA",
    "ITEM_DESCRIPTION": "BBQ - WOOD SINGLE"
  },
  {
    "PARK_NAME": "MCDOWALL RESERVE",
    "SUBURB": "MCDOWALL",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "POOH CORNER",
    "SUBURB": "WACOL",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "ANZAC PARK",
    "SUBURB": "MOUNT COOT-THA",
    "ITEM_DESCRIPTION": "BBQ - WOOD SINGLE"
  },
  {
    "PARK_NAME": "PHIL DENMAN PARK",
    "SUBURB": "JAMBOREE HEIGHTS",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "GLINDEMANN PARK",
    "SUBURB": "HOLLAND PARK WEST",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "DEAGON SPORTSGROUND PARK",
    "SUBURB": "DEAGON",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "PASK FAMILY PARK",
    "SUBURB": "ROCHEDALE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "MACARANGA CRESCENT PARK",
    "SUBURB": "CARSELDINE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "CROSBY PARK",
    "SUBURB": "ALBION",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "THE LAKE PARKLANDS",
    "SUBURB": "FOREST LAKE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "FOREST LAKE LIONS PARK",
    "SUBURB": "FOREST LAKE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "ASCOT PARK",
    "SUBURB": "ASCOT",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "NIXON PARK",
    "SUBURB": "OXLEY",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "PALLARA PARK",
    "SUBURB": "PALLARA",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "KERRIA STREET PARK",
    "SUBURB": "BELLBOWRIE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "HONEYEATER STREET PARK",
    "SUBURB": "UPPER KEDRON",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "MELALEUCA GREEN PARK",
    "SUBURB": "CHERMSIDE WEST",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "WISHART COMMUNITY PARK",
    "SUBURB": "WISHART",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "NICHOLSON PLACE PARK",
    "SUBURB": "NORTHGATE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "HANLON PARK / BUR'UDA",
    "SUBURB": "GREENSLOPES",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "SHERWOOD ARBORETUM",
    "SUBURB": "SHERWOOD",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "KALINGA PARK",
    "SUBURB": "CLAYFIELD",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "LES ATKINSON PARK",
    "SUBURB": "SUNNYBANK",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "SIR JOHN CHANDLER PARK",
    "SUBURB": "INDOOROOPILLY",
    "ITEM_DESCRIPTION": "BBQ - WOOD SINGLE"
  },
  {
    "PARK_NAME": "STUDLEY PARK",
    "SUBURB": "WAVELL HEIGHTS",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "BARRETT STREET PARK (WATER RESERVE)",
    "SUBURB": "BRACKEN RIDGE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "JOSEPH LEE PARK",
    "SUBURB": "ZILLMERE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "WYNNUM WADING POOL PARK",
    "SUBURB": "WYNNUM",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "PERRY PARK",
    "SUBURB": "BOWEN HILLS",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "RAY LYNCH PARK",
    "SUBURB": "HOLLAND PARK",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "WOOLCOCK PARK",
    "SUBURB": "RED HILL",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "BOWMAN PARK",
    "SUBURB": "BARDON",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "KINTA STREET PARK",
    "SUBURB": "KURABY",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "NILKERIE STREET PARK",
    "SUBURB": "CARSELDINE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "FIG TREE POCKET RIVERSIDE RESERVE",
    "SUBURB": "FIG TREE POCKET",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "THORNYCROFT STREET PARK",
    "SUBURB": "TARRAGINDI",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "LOTA CAMPING RESERVE",
    "SUBURB": "LOTA",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "ORLEIGH PARK",
    "SUBURB": "WEST END",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "MT COOT-THA RESERVE",
    "SUBURB": "MOUNT COOT-THA",
    "ITEM_DESCRIPTION": "BBQ - GAS SINGLE"
  },
  {
    "PARK_NAME": "MT COOT-THA RESERVE",
    "SUBURB": "MOUNT COOT-THA",
    "ITEM_DESCRIPTION": "BBQ - WOOD SINGLE"
  },
  {
    "PARK_NAME": "ANSTEAD BUSHLAND RESERVE",
    "SUBURB": "ANSTEAD",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "PRESTON ROAD PARK",
    "SUBURB": "CARINA",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "KIANAWAH ROAD PARK (NO.330)",
    "SUBURB": "WYNNUM WEST",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "CARINYA STREET PARK",
    "SUBURB": "INDOOROOPILLY",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "KANGAROO POINT CLIFFS PARK",
    "SUBURB": "KANGAROO POINT",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "MERTHYR PARK",
    "SUBURB": "NEW FARM",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "KANGAROO POINT CLIFFS PARK",
    "SUBURB": "KANGAROO POINT",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "KURILPA POINT PARK",
    "SUBURB": "SOUTH BRISBANE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "KANGAROO POINT CLIFFS PARK",
    "SUBURB": "KANGAROO POINT",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "FIDDLEWOOD CRESCENT PARK",
    "SUBURB": "BELLBOWRIE",
    "ITEM_DESCRIPTION": "BBQ - WOOD SINGLE"
  },
  {
    "PARK_NAME": "HEMMANT RECREATION RESERVE",
    "SUBURB": "HEMMANT",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "ORIEL PARK",
    "SUBURB": "ASCOT",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "MT COOT-THA RESERVE",
    "SUBURB": "MOUNT COOT-THA",
    "ITEM_DESCRIPTION": "BBQ - GAS DOUBLE (SOLAR IGNITION)"
  },
  {
    "PARK_NAME": "MT COOT-THA RESERVE",
    "SUBURB": "MOUNT COOT-THA",
    "ITEM_DESCRIPTION": "BBQ - GAS SINGLE"
  },
  {
    "PARK_NAME": "MT COOT-THA RESERVE",
    "SUBURB": "MOUNT COOT-THA",
    "ITEM_DESCRIPTION": "BBQ - WOOD SINGLE"
  },
  {
    "PARK_NAME": "NELSON PLACE PARK",
    "SUBURB": "NEWMARKET",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "SIR JAMES KILLEN RESERVE",
    "SUBURB": "SUNNYBANK HILLS",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "JINDALEE PARK",
    "SUBURB": "JINDALEE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "FAULKNER PARK",
    "SUBURB": "GRACEVILLE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "PATONGA STREET PARK",
    "SUBURB": "BANYO",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "FENWICK PARK",
    "SUBURB": "MITCHELTON",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "THE RAFTING GROUND PARK",
    "SUBURB": "BROOKFIELD",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "BILL LAMOND PARK",
    "SUBURB": "LOTA",
    "ITEM_DESCRIPTION": "BBQ - WOOD SINGLE"
  },
  {
    "PARK_NAME": "BISSET PLACE PARK",
    "SUBURB": "MCDOWALL",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "WYNNUM WADING POOL PARK",
    "SUBURB": "WYNNUM",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "BILL BROWN SPORTS RESERVE",
    "SUBURB": "FITZGIBBON",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "BREAKWATER PARK",
    "SUBURB": "WYNNUM",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "ROBERTSON PARK",
    "SUBURB": "TARINGA",
    "ITEM_DESCRIPTION": "BBQ - WOOD SINGLE"
  },
  {
    "PARK_NAME": "BAYSIDE PARK",
    "SUBURB": "MANLY",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "TENNIS AVENUE PARK",
    "SUBURB": "ASHGROVE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "MOOLABIN PARK",
    "SUBURB": "MOOROOKA",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "WALTON BRIDGE RESERVE",
    "SUBURB": "THE GAP",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "SHERWOOD ARBORETUM",
    "SUBURB": "SHERWOOD",
    "ITEM_DESCRIPTION": "BBQ - WOOD SINGLE"
  },
  {
    "PARK_NAME": "7TH BRIGADE PARK",
    "SUBURB": "CHERMSIDE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "VICTOR GRENNING PARK",
    "SUBURB": "ZILLMERE",
    "ITEM_DESCRIPTION": "BBQ - WOOD SINGLE"
  },
  {
    "PARK_NAME": "PARKINSON RECREATIONAL RESERVE",
    "SUBURB": "PARKINSON",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "MOORA PARK",
    "SUBURB": "SHORNCLIFFE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "MT CROSBY SPORTSGROUND",
    "SUBURB": "CHUWAR",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "MCLEOD COURT PARK",
    "SUBURB": "MCDOWALL",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "GOULD ROAD PARK",
    "SUBURB": "HERSTON",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "REGENCY PLACE PARK (NO.16)",
    "SUBURB": "STRETTON",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "WATERFRONT PARK",
    "SUBURB": "NEWSTEAD",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "CARINYA STREET PARK",
    "SUBURB": "INDOOROOPILLY",
    "ITEM_DESCRIPTION": "BBQ - WOOD SINGLE"
  },
  {
    "PARK_NAME": "MT COOT-THA RESERVE",
    "SUBURB": "MOUNT COOT-THA",
    "ITEM_DESCRIPTION": "BBQ - GAS DOUBLE (SOLAR IGNITION)"
  },
  {
    "PARK_NAME": "KEN FLETCHER PARK",
    "SUBURB": "TENNYSON",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "CICADA PARK",
    "SUBURB": "CHAPEL HILL",
    "ITEM_DESCRIPTION": "BBQ - WOOD SINGLE"
  },
  {
    "PARK_NAME": "SIR JOHN CHANDLER PARK",
    "SUBURB": "INDOOROOPILLY",
    "ITEM_DESCRIPTION": "BBQ - WOOD SINGLE"
  },
  {
    "PARK_NAME": "KIMBERLY PARK",
    "SUBURB": "FITZGIBBON",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "KURINGGAI PARK",
    "SUBURB": "FITZGIBBON",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "MT COOT-THA RESERVE",
    "SUBURB": "MOUNT COOT-THA",
    "ITEM_DESCRIPTION": "BBQ - GAS DOUBLE (SOLAR IGNITION)"
  },
  {
    "PARK_NAME": "SILKYOAK CIRCUIT PARK",
    "SUBURB": "FITZGIBBON",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "WALLABY PARADE PARK",
    "SUBURB": "ROCHEDALE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "BERKSHIRE CRESCENT PARK",
    "SUBURB": "WISHART",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "ANZAC PARK",
    "SUBURB": "MOUNT COOT-THA",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "MOGGILL DISTRICT SPORT PARK",
    "SUBURB": "MOGGILL",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "KEPERRA PICNIC GROUND PARK",
    "SUBURB": "FERNY GROVE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "BARBOUR ROAD PARK",
    "SUBURB": "BRACKEN RIDGE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "HUTCHISON PARK",
    "SUBURB": "SHORNCLIFFE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "MAGGS STREET PARK",
    "SUBURB": "WAVELL HEIGHTS",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "C.J.GREENFIELD COMPLEX PARK",
    "SUBURB": "RICHLANDS",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "MOORLANDS PARK",
    "SUBURB": "AUCHENFLOWER",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "MT COOT-THA RESERVE",
    "SUBURB": "MOUNT COOT-THA",
    "ITEM_DESCRIPTION": "BBQ - GAS DOUBLE (SOLAR IGNITION)"
  },
  {
    "PARK_NAME": "KOOKABURRA PARK",
    "SUBURB": "ROCKLEA",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "WALLAROO WAY COMMUNITY PARK",
    "SUBURB": "DOOLANDELLA",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "JOHN SPRENT RESERVE",
    "SUBURB": "MOGGILL",
    "ITEM_DESCRIPTION": "BBQ - GAS DOUBLE (SOLAR IGNITION)"
  },
  {
    "PARK_NAME": "NEWCOMB PARK",
    "SUBURB": "RIVERHILLS",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "GRINSTEAD PARK",
    "SUBURB": "ALDERLEY",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "BULIMBA RIVERSIDE PARK",
    "SUBURB": "BULIMBA",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "SHERWOOD ARBORETUM",
    "SUBURB": "SHERWOOD",
    "ITEM_DESCRIPTION": "BBQ - WOOD SINGLE"
  },
  {
    "PARK_NAME": "FAVERSHAM STREET PARK",
    "SUBURB": "WOOLLOONGABBA",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "JEAYS STREET PARK",
    "SUBURB": "BOWEN HILLS",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "GIBSON PARK",
    "SUBURB": "STAFFORD",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "HINCHINBROOK CIRCUIT PARK",
    "SUBURB": "FOREST LAKE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "7TH BRIGADE PARK",
    "SUBURB": "CHERMSIDE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "HUXTABLE PARK",
    "SUBURB": "CHERMSIDE WEST",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "AKUNA STREET PARK",
    "SUBURB": "KENMORE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "SEDGLEY PARK",
    "SUBURB": "ALDERLEY",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "HAROLD KIELLY PARK",
    "SUBURB": "BALD HILLS",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "YIMBUN PARK",
    "SUBURB": "SUNNYBANK",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "ROCKS RIVERSIDE PARK",
    "SUBURB": "SEVENTEEN MILE ROCKS",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "TINGALPA CREEK RESERVE",
    "SUBURB": "CHANDLER",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "ALGESTER ROAD PARK (NO.515)",
    "SUBURB": "PARKINSON",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "YERONGA MEMORIAL PARK",
    "SUBURB": "YERONGA",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "TINCHI TAMBA WETLANDS RESERVE",
    "SUBURB": "BALD HILLS",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "MULBEAM PARK",
    "SUBURB": "BOONDALL",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "LAKEWOOD AVENUE PARK",
    "SUBURB": "PARKINSON",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "TRANQUIL PARK",
    "SUBURB": "SUNNYBANK HILLS",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "WHITMORE STREET PARK",
    "SUBURB": "TARINGA",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "TERALBA PARK",
    "SUBURB": "EVERTON PARK",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "RAINWORTH PARK",
    "SUBURB": "BARDON",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "WESTBROOK PARK",
    "SUBURB": "TOOWONG",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "LEACROFT ROAD PARK",
    "SUBURB": "BURBANK",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "COLMSLIE RESERVE",
    "SUBURB": "MORNINGSIDE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "MT COOT-THA RESERVE",
    "SUBURB": "MOUNT COOT-THA",
    "ITEM_DESCRIPTION": "BBQ - GAS SINGLE"
  },
  {
    "PARK_NAME": "MT COOT-THA RESERVE",
    "SUBURB": "MOUNT COOT-THA",
    "ITEM_DESCRIPTION": "BBQ - WOOD SINGLE"
  },
  {
    "PARK_NAME": "FAUNA PARADE PARK",
    "SUBURB": "ROCKLEA",
    "ITEM_DESCRIPTION": "BBQ - WOOD SINGLE"
  },
  {
    "PARK_NAME": "FLYNN OVAL PARK",
    "SUBURB": "WINDSOR",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "D.J.SHERRINGTON PARK",
    "SUBURB": "INALA",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "7TH BRIGADE PARK",
    "SUBURB": "CHERMSIDE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "GEORGE CLAYTON PARK",
    "SUBURB": "MANLY",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "SUMMIT STREET PARK",
    "SUBURB": "BELMONT",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "WILHELMINE KRUGER PARK",
    "SUBURB": "NUDGEE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "KANGAROO POINT CLIFFS PARK",
    "SUBURB": "KANGAROO POINT",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "CAPTAIN BURKE PARK",
    "SUBURB": "KANGAROO POINT",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "KANGAROO POINT CLIFFS PARK",
    "SUBURB": "KANGAROO POINT",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "BOOKER PLACE PARK",
    "SUBURB": "BELLBOWRIE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "PLAISTED PLACE PARK",
    "SUBURB": "NORTHGATE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "MT CROSBY SPORTSGROUND",
    "SUBURB": "CHUWAR",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "MT COOT-THA RESERVE",
    "SUBURB": "MOUNT COOT-THA",
    "ITEM_DESCRIPTION": "BBQ - GAS SINGLE (SOLAR IGNITION)"
  },
  {
    "PARK_NAME": "MT COOT-THA RESERVE",
    "SUBURB": "MOUNT COOT-THA",
    "ITEM_DESCRIPTION": "BBQ - GAS DOUBLE (SOLAR IGNITION)"
  },
  {
    "PARK_NAME": "MT COOT-THA RESERVE",
    "SUBURB": "MOUNT COOT-THA",
    "ITEM_DESCRIPTION": "BBQ - GAS DOUBLE (SOLAR IGNITION)"
  },
  {
    "PARK_NAME": "CARINDALE RECREATION RESERVE",
    "SUBURB": "CARINDALE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "PERTH STREET PARK",
    "SUBURB": "CAMP HILL",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "WHIPBIRD PARK",
    "SUBURB": "MACGREGOR",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "LOTA POINT PARK (ROAD RESERVE)",
    "SUBURB": "LOTA",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "TERALBA PARK",
    "SUBURB": "EVERTON PARK",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "KIANAWAH ROAD PARK (NO.330)",
    "SUBURB": "WYNNUM WEST",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "LORIKEET PARK",
    "SUBURB": "MOUNT OMMANEY",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "COOLABAH CRESCENT PARK",
    "SUBURB": "BRIDGEMAN DOWNS",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "SHAW ESTATE PARK",
    "SUBURB": "WAVELL HEIGHTS",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "THRUSH STREET PARK",
    "SUBURB": "INALA",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "TINCHI TAMBA WETLANDS RESERVE",
    "SUBURB": "BALD HILLS",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "NUDGEE BEACH RESERVE",
    "SUBURB": "NUDGEE BEACH",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "TOOHEY FOREST PARK",
    "SUBURB": "NATHAN",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "KURILPA POINT PARK",
    "SUBURB": "SOUTH BRISBANE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "MT COOT-THA RESERVE",
    "SUBURB": "MOUNT COOT-THA",
    "ITEM_DESCRIPTION": "BBQ - WOOD SINGLE"
  },
  {
    "PARK_NAME": "ILLAWONG RESERVE",
    "SUBURB": "KARANA DOWNS",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "THE LAKE PARKLANDS",
    "SUBURB": "FOREST LAKE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "SANDY CREEK PARK",
    "SUBURB": "TARRAGINDI",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "WHITES HILL RESERVE",
    "SUBURB": "CAMP HILL",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "FERNY GROVE PICNIC GROUND PARK",
    "SUBURB": "FERNY GROVE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "BIAMI YUMBA PARK",
    "SUBURB": "FIG TREE POCKET",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "MT COOT-THA RESERVE",
    "SUBURB": "MOUNT COOT-THA",
    "ITEM_DESCRIPTION": "BBQ - GAS DOUBLE"
  },
  {
    "PARK_NAME": "ST LUCIA PLAYGROUND PARK",
    "SUBURB": "ST LUCIA",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "WAKERLEY PARK",
    "SUBURB": "WAKERLEY",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "MT COOT-THA RESERVE",
    "SUBURB": "MOUNT COOT-THA",
    "ITEM_DESCRIPTION": "BBQ - GAS DOUBLE (SOLAR IGNITION)"
  },
  {
    "PARK_NAME": "LORIKEET PARK (ALGESTER)",
    "SUBURB": "ALGESTER",
    "ITEM_DESCRIPTION": "BBQ - WOOD SINGLE"
  },
  {
    "PARK_NAME": "BECCARIA PARK",
    "SUBURB": "DOOLANDELLA",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "PROGRESS PARK",
    "SUBURB": "NORTHGATE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "KOOKABURRA CIRCUIT PARK",
    "SUBURB": "ROCHEDALE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "MT COOT-THA RESERVE",
    "SUBURB": "MOUNT COOT-THA",
    "ITEM_DESCRIPTION": "BBQ - GAS DOUBLE (SOLAR IGNITION)"
  },
  {
    "PARK_NAME": "KARAWATHA FOREST PARK",
    "SUBURB": "KARAWATHA",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "KARAWATHA FOREST PARK",
    "SUBURB": "KARAWATHA",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "WESTON PLACE PARK",
    "SUBURB": "OXLEY",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "ORLEIGH PARK",
    "SUBURB": "WEST END",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "FERNY GROVE PICNIC GROUND PARK",
    "SUBURB": "FERNY GROVE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "TUCKEROO PARK",
    "SUBURB": "NUDGEE BEACH",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "WAKEFIELD PARK",
    "SUBURB": "BRIGHTON",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "PORTER'S PADDOCK PARK",
    "SUBURB": "TINGALPA",
    "ITEM_DESCRIPTION": "BBQ - GAS DOUBLE (SOLAR IGNITION)"
  },
  {
    "PARK_NAME": "MEADOWLANDS PICNIC GROUND PARK",
    "SUBURB": "TINGALPA",
    "ITEM_DESCRIPTION": "BBQ - WOOD SINGLE"
  },
  {
    "PARK_NAME": "ABBEVILLE STREET PARK",
    "SUBURB": "UPPER MOUNT GRAVATT",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "GREENE PARK",
    "SUBURB": "WYNNUM",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "MONIER ROAD PARK (NOS.44-84)",
    "SUBURB": "DARRA",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "PRIMROSE PARK",
    "SUBURB": "WYNNUM WEST",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "SANDGATE FORESHORES PARK",
    "SUBURB": "SANDGATE",
    "ITEM_DESCRIPTION": "BBQ - WOOD SINGLE"
  },
  {
    "PARK_NAME": "GREGORY PARK",
    "SUBURB": "MILTON",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "MORTIMER ROAD PARK",
    "SUBURB": "ACACIA RIDGE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "7TH BRIGADE PARK",
    "SUBURB": "CHERMSIDE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "BOLTON STREET PARK",
    "SUBURB": "EIGHT MILE PLAINS",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "BILL MCFARLANE PARK",
    "SUBURB": "WAKERLEY",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "SANDGATE SECOND LAGOON RESERVE",
    "SUBURB": "SANDGATE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "FIG TREE POCKET RIVERSIDE RESERVE",
    "SUBURB": "FIG TREE POCKET",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "DORRINGTON PARK",
    "SUBURB": "ASHGROVE",
    "ITEM_DESCRIPTION": "BBQ - WOOD DOUBLE"
  },
  {
    "PARK_NAME": "CARINDALE RECREATION RESERVE",
    "SUBURB": "CARINDALE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "WINDSOR PARK",
    "SUBURB": "WINDSOR",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "TWILIGHT STREET PARK",
    "SUBURB": "KENMORE",
    "ITEM_DESCRIPTION": "BBQ - WOOD SINGLE"
  },
  {
    "PARK_NAME": "SANDGATE FORESHORES PARK",
    "SUBURB": "SANDGATE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "SEDGLEY PARK",
    "SUBURB": "ALDERLEY",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "GUM NUT NOOK",
    "SUBURB": "MCDOWALL",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "KERRY ROAD PARK",
    "SUBURB": "ARCHERFIELD",
    "ITEM_DESCRIPTION": "BBQ - WOOD SINGLE"
  },
  {
    "PARK_NAME": "KALINGA PARK",
    "SUBURB": "CLAYFIELD",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "BRUSHBOX PARK",
    "SUBURB": "UPPER MOUNT GRAVATT",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "RAVEN STREET RESERVE",
    "SUBURB": "CHERMSIDE WEST",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "JUBILEE AVENUE PARK",
    "SUBURB": "FOREST LAKE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "COORA STREET PARK",
    "SUBURB": "WISHART",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "SHAFTESBURY STREET PARK",
    "SUBURB": "TARRAGINDI",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "DECKER PARK",
    "SUBURB": "BRIGHTON",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "DECKER PARK",
    "SUBURB": "BRIGHTON",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "C.A.O SULLIVAN PARK",
    "SUBURB": "ACACIA RIDGE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "ANSTEAD BUSHLAND RESERVE",
    "SUBURB": "ANSTEAD",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "JACK PYLE PARK",
    "SUBURB": "SUNNYBANK HILLS",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "J.C.TROTTER MEMORIAL PARK",
    "SUBURB": "BURBANK",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "WYANDRA CRESCENT PARK",
    "SUBURB": "MURARRIE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "SANDGATE FORESHORES PARK",
    "SUBURB": "SANDGATE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "WOOLLOONGABBA ROTARY PARK",
    "SUBURB": "EAST BRISBANE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "7TH BRIGADE PARK",
    "SUBURB": "CHERMSIDE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "ST ANDREWS AVENUE PARK",
    "SUBURB": "FOREST LAKE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "BOOKER PLACE PARK",
    "SUBURB": "BELLBOWRIE",
    "ITEM_DESCRIPTION": "BBQ - WOOD SINGLE"
  },
  {
    "PARK_NAME": "KANGAROO POINT CLIFFS PARK",
    "SUBURB": "KANGAROO POINT",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "KANGAROO POINT CLIFFS PARK",
    "SUBURB": "KANGAROO POINT",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "ROCKS RIVERSIDE PARK",
    "SUBURB": "SEVENTEEN MILE ROCKS",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "UPPER KEDRON RECREATION RESERVE",
    "SUBURB": "UPPER KEDRON",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "TUCKEROO PARK",
    "SUBURB": "NUDGEE BEACH",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "RAINBOW LORIKEET PARK",
    "SUBURB": "ASPLEY",
    "ITEM_DESCRIPTION": "BBQ - WOOD SINGLE"
  },
  {
    "PARK_NAME": "MT COOT-THA RESERVE",
    "SUBURB": "MOUNT COOT-THA",
    "ITEM_DESCRIPTION": "BBQ - WOOD SINGLE"
  },
  {
    "PARK_NAME": "MT COOT-THA RESERVE",
    "SUBURB": "MOUNT COOT-THA",
    "ITEM_DESCRIPTION": "BBQ - GAS DOUBLE"
  },
  {
    "PARK_NAME": "MARCHANT PARK",
    "SUBURB": "ASPLEY",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "HEATHWOOD PARK",
    "SUBURB": "HEATHWOOD",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "WATHEROO PLACE PARK",
    "SUBURB": "PARKINSON",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "NEW FARM PARK",
    "SUBURB": "NEW FARM",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "DUNLOP PARK",
    "SUBURB": "CORINDA",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "JOHN WALKER PLACE",
    "SUBURB": "YERONGA",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "VIC LUCAS PARK",
    "SUBURB": "BULIMBA",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "EUNGELLA TERRACE PARK",
    "SUBURB": "FOREST LAKE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "EUNGELLA TERRACE PARK",
    "SUBURB": "FOREST LAKE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "NEW FARM PARK",
    "SUBURB": "NEW FARM",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "NEW FARM PARK",
    "SUBURB": "NEW FARM",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "MOOROOKA LIONS BICENT. PICNIC GRND PARK",
    "SUBURB": "YEERONGPILLY",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "7TH BRIGADE PARK",
    "SUBURB": "CHERMSIDE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "NORMA CROKER PARK",
    "SUBURB": "ACACIA RIDGE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "THRUSH STREET PARK",
    "SUBURB": "INALA",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "SANDGATE FORESHORES PARK",
    "SUBURB": "SANDGATE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "BAYSIDE PARK",
    "SUBURB": "MANLY",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "SURBITON COURT PARK",
    "SUBURB": "CARINDALE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "SHERWOOD ARBORETUM",
    "SUBURB": "SHERWOOD",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "GUS DAVIES PARK",
    "SUBURB": "BALD HILLS",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "TARINGA PLAYGROUND PARK",
    "SUBURB": "TARINGA",
    "ITEM_DESCRIPTION": "BBQ - WOOD SINGLE"
  },
  {
    "PARK_NAME": "BARRETT STREET PARK (WATER RESERVE)",
    "SUBURB": "BRACKEN RIDGE",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "ROCKS RIVERSIDE PARK",
    "SUBURB": "SEVENTEEN MILE ROCKS",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "HINKLER PARK",
    "SUBURB": "WINDSOR",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "WOOLCOCK PARK",
    "SUBURB": "RED HILL",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "PERRIN PARK",
    "SUBURB": "TOOWONG",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "KANGAROO POINT CLIFFS PARK",
    "SUBURB": "KANGAROO POINT",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "TORRENS CRESCENT PARK",
    "SUBURB": "WAKERLEY",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "WITTONGA PARK",
    "SUBURB": "THE GAP",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "GUYATT PARK",
    "SUBURB": "ST LUCIA",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "NEW FARM PARK",
    "SUBURB": "NEW FARM",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "DUCIE STREET PARK",
    "SUBURB": "DARRA",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "CLIFTON HILL PEACE PARK",
    "SUBURB": "ANNERLEY",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "FITZGIBBON BUSHLANDS",
    "SUBURB": "FITZGIBBON",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "HERCULES STREET PARK",
    "SUBURB": "HAMILTON",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "GRACEVILLE RIVERSIDE PARKLANDS",
    "SUBURB": "GRACEVILLE",
    "ITEM_DESCRIPTION": "BBQ - WOOD SINGLE"
  },
  {
    "PARK_NAME": "JOSEPH LEE PARK",
    "SUBURB": "ZILLMERE",
    "ITEM_DESCRIPTION": "BBQ - WOOD DOUBLE"
  },
  {
    "PARK_NAME": "ALBERT BISHOP PARK",
    "SUBURB": "NUNDAH",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC SINGLE"
  },
  {
    "PARK_NAME": "HAMILTON PARK",
    "SUBURB": "HAMILTON",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  },
  {
    "PARK_NAME": "REGENCY PLACE PARK (NO.16)",
    "SUBURB": "STRETTON",
    "ITEM_DESCRIPTION": "BBQ - ELECTRIC DOUBLE"
  }
]
